### model
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all

### dataset
dataset: airdrop_webpage
template: llama3
cutoff_len: 10240
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3_1-8b/lora/sft
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
dataloader_num_workers: 3
weight_decay: 0.01
temperature: 0.1

### eval
val_size: 0.3
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20
